module.exports = {
  plugins: {
    "@fullhuman/postcss-purgecss": {
      content: ["./hugo_stats.json"],
      defaultExtractor: (content) => {
        let els = JSON.parse(content).htmlElements;
        return els.tags.concat(els.classes, els.ids);
      },
      safelist: {
        standard: [
          "rouge",
          "copy-button",
          "tooltip", 
          "tooltipstered",
          "topnav",
          "nav",
          "permanentTopNav",
          "input",
          "far",
          "search",
          "search-box",
          "fas", 
          "fa-search",
          "fa-clipboard",
          "search",
          "highlight",
          "pre",
          "video",
          "code",
          "content",
          "h3",
          "h4",
          "ul",
          "li",
          "gh",
          "sr",
          "go",
          "gp",
          "gs",
          "gu",
          "nb",
          "cm",
          "cp",
          "c1",
          "cs",
          "c",
          "ch",
          "cd",
          "cpf",
          "err",
          "gr",
          "gt",
          "gd",
          "gi",
          "ge",
          "kc",
          "kd",
          "kr",
          "no",
          "kt",
          "mf",
          "mh",
          "il",
          "mi",
          "mo",
          "m",
          "mb",
          "mx",
          "sc",
          "se",
          "ss",
          "sd",
          "s2",
          "sb",
          "sh",
          "si",
          "sx",
          "s1",
          "s",
          "sa",
          "dl",
          "na",
          "nc",
          "nd",
          "ne",
          "nf",
          "fm",
          "vc",
          "nn",
          "nl",
          "ni",
          "bp",
          "vg",
          "vi",
          "nv",
          "vm",
          "w",
          "n",
          "py",
          "nx",
          "ow",
          "nt",
          "k",
          "kv",
          "kn",
          "kp",
          "o",
        ],
        deep: [],
        greedy: [],
        keyframes: [],
        variables: [],
      },
      fontFace: true,
    },
    autoprefixer: {},
    cssnano: { preset: "default" },
  },
};
