name: Check dead links

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 6'

jobs:
  asciidoc-link-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 16.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g asciidoc-link-check
    - run: find . -name \*.adoc -exec asciidoc-link-check -c config.json --progress {} \;
